

upstream localhost {
    server emovision-streaming_gateway_1:5001;
    server emovision-streaming_gateway_2:5001;
    server emovision-streaming_gateway_3:5001;
    # server gateway4:5001;
}
server {
    listen 8080;
    server_name localhost;
    client_max_body_size 10M;
    location /nginx_status {
 	    stub_status;
    }
    location / {
        proxy_pass http://localhost;
        proxy_set_header Host $host;
    }
    
}
