upstream uwsgi {
    least_conn;
    server 192.168.0.111:7010;
    server 192.168.0.111:7009;
    server 192.168.0.111:7008;
    server 192.168.0.111:7007;
    server 192.168.0.111:7006;
    server 192.168.0.111:7005;
    server 192.168.0.111:7004;
    server 192.168.0.111:7003;
    server 192.168.0.111:7002;
    server 192.168.0.111:7001;
}
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}
# configuration of the server
server {
    # the port your site will be served on
    listen    80;
    # the domain name it will serve for
    # substitute your machine's IP address or FQDN
    # server_name  192.18.0.111;
    charset     utf-8;

    client_max_body_size 4G;   # adjust to taste

    location / {
        proxy_pass  http://uwsgi;
        # include     /etc/nginx/uwsgi_params; # the uwsgi_params file you installed
        #proxy_connect_timeout 10m;
        #proxy_buffering off;
        #proxy_send_timeout   10m;
        #proxy_read_timeout   10m;
	    proxy_http_version 1.1;
	    proxy_set_header Upgrade $http_upgrade;
	    proxy_set_header Connection $connection_upgrade;

        proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header Host $host;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #uwsgi_buffering off;
    }
}