[uwsgi]
master=true
# maximum number of worker processes
processes=1
module=app_plasma_new:app
gevent = 100
http-websockets = true
http = true
socket = :5050
py-autoreload = 1
http-timeout = 600
websocket-pong-tolerance = 3600
buffer-size=65535


# clear environment on exit
vacuum          = true